### ISSUE TITLE
<Mrkdwn> return a lot of error

### ISSUE THREAD

**Issue by blademckain** [speee/jsx-slack#115]
using the tag <Mrkdwn....></Mrkdwn>
generate a lot of error

I have also tried the example in
https://api.slack.com/reference/block-kit/composition-objects#text
but it generate this error:

[
  {
    type: 'section',
    text: {
      type: 'mrkdwn',
      text: 'https://example.com/',
      verbatim: '{false}'
    }
  },
  { type: 'section', fields: [ [Object] ] },
  { type: 'context', elements: [ [Object], [Object] ] }
]
2020-02-17T07:19:16.014Z	3523c5bf-21ca-4f9f-b2a2-23712cebaff4	ERROR	Error: An API error occurred: invalid_blocks
    at Object.platformErrorFromResult (/var/task/node_modules/@slack/web-api/dist/errors.js:50:33)
    at WebClient.apiCall (/var/task/node_modules/@slack/web-api/dist/WebClient.js:465:28)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at module.exports (/var/task/api/lansweeper-events.js:107:17)
    at Server.<anonymous> (/var/task/___now_helpers.js:875:13) {
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'invalid_blocks',
    response_metadata: { messages: [Array], scopes: [Array], acceptedScopes: [Array] }
  }
}

**Comment by yhatt** [comment]
Perhaps `verbatim: '{false}'` is invalid. It must be `verbatim: false`.

You might be using invalid JSX syntax `{}` in `jsxslack` template literal. It must be `${}`. [See also HTM syntax.](https://github.com/developit/htm/blob/master/README.md#syntax-like-jsx-but-also-lit)

```javascript
import { jsxslack } from '@speee-js/jsx-slack'

// Wrong
console.log(jsxslack`
  <Blocks>
    <Section>
      <Mrkdwn verbatim={false}>
        https://example.com/
      </Mrkdwn>
    </Section>
  </Blocks>
`)

// Correct
console.log(jsxslack`
  <Blocks>
    <Section>
      <Mrkdwn verbatim=${false}>
        https://example.com/
      </Mrkdwn>
    </Section>
  </Blocks>
`)
```
